In [40]:
import pandas as pd

In [41]:
df = pd.read_csv('returns.txt')

In [42]:
df.head(5)

         Order Id Return Reason
0  CA-2020-104689   Wrong Items
1  CA-2020-105081   Wrong Items
2  CA-2020-105291   Wrong Items
3  CA-2020-105585   Wrong Items
4  CA-2020-106950   Wrong Items

In [43]:
dfo = pd.read_csv('orders.txt')

In [44]:

df.rename(columns={'Return Reason':'return_reason'}, inplace = True)
x = df['return_reason'].unique()
print(x)

['Wrong Items' nan 'Bad Quality' 'Others']

In [45]:
# write a program to get category wise sales of orders that were not returned
return_df = df['Order Id'].unique()
orders_df = dfo[~dfo['order_id'].isin(return_df)]
orders_df.groupby('category').agg({'sales':'sum'})

                       sales
category
Furniture        582415.6449
Office Supplies  284516.2270
Technology       174630.6580

In [46]:
df.rename(columns={'Order Id':'order_id'}, inplace = True)

In [47]:
#write a program to get city wise count of return orders
city_df = pd.merge(dfo, df, how='left', on = 'order_id')
city_df['city'].value_counts()

city
New York City    450
Los Angeles      384
Philadelphia     265
San Francisco    265
Seattle          212
                ...
Burbank            1
Glenview           1
Jupiter            1
Ormond Beach       1
Elkhart            1
Name: count, Length: 531, dtype: int64

In [48]:
# write a program to print cities where we have all 3 kinds of returns (others,bad quality,wrong items)
city_return = pd.merge(dfo,df,how='left',on = 'order_id')
city_ret_counts = city_return.groupby('city')['return_reason'].nunique()
city_ret_counts[city_ret_counts.values > 1]

city
Chicago          2
Columbus         2
Costa Mesa       2
Denver           2
Fairfield        2
Houston          2
Jackson          2
Lakewood         2
Los Angeles      3
Lowell           2
New York City    3
Oakland          2
Pasadena         2
San Diego        2
San Francisco    2
Seattle          2
Springfield      2
Name: return_reason, dtype: int64

In [49]:
# write a program to find top 3 cities by sales
dfo.groupby('city')['sales'].sum().sort_values(ascending=False).head(3)

city
New York City    115073.919
Los Angeles       79663.299
San Francisco     52590.648
Name: sales, dtype: float64

In [50]:
df[df['return_reason'].isna()]

           order_id return_reason
11   CA-2020-114307           NaN
29   CA-2020-133368           NaN
107  CA-2018-105270           NaN
142  CA-2018-164721           NaN
149  CA-2019-105158           NaN

In [51]:
df['return_reason'].fillna('others',inplace = True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11588\3782146756.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['return_reason'].fillna('others',inplace = True)

In [54]:
dfo.groupby('category').agg({'sales':'mean','profit':'mean'})

                      sales     profit
category
Furniture        356.212758   9.813403
Office Supplies  107.680040  18.906134
Technology       382.705186  75.452770

In [52]:
dfo.head()

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288