In [3]:
import pandas as pd

In [12]:
file_path = 'fab4.xlsx'
k_df = pd.read_excel(file_path, sheet_name = 'Kane',index_col = None)
k_df.head(15)

,Country,Span,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100s,50s,0s,4s,6s
0,in Australia,2011-2019,7,14,1,557,166,42.84,867,64.24,2,1,2,78,0
1,in Bangladesh,2013-2023,4,7,0,389,114,55.57,778,50.00,2,2,0,37,1
2,in England,2013-2022,8,16,1,458,132,30.53,1171,39.11,1,2,1,57,0
3,in India,2010-2021,8,15,0,503,131,33.53,1251,40.20,1,3,1,51,0
4,in New Zealand,2011-2024,52,87,10,5142,251,66.77,9351,54.98,20,21,4,580,20
5,in Pakistan,2022-2023,2,3,1,277,200*,138.50,593,46.71,1,0,0,32,1
6,in South Africa,2013-2016,4,7,1,127,77,21.16,262,48.47,0,1,0,15,1
7,in Sri Lanka,2012-2024,6,11,0,325,135,29.54,701,46.36,1,1,2,26,2
8,in U.A.E.,2014-2018,6,11,1,647,192,64.70,1145,56.50,2,2,0,62,1
9,in West Indies,2012-2014,5,10,1,462,161*,51.33,1129,40.92,2,1,1,54,0
10,in Zimbabwe,2011-2016,3,5,1,389,113,97.25,665,58.49,1,3,0,39,1

In [13]:
file_path = 'fab4.xlsx'
k_df = pd.read_excel(file_path, sheet_name = 'Virat',index_col = None)
k_df.head(15)

,Country,Span,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100s,50s,0s,4s,6s
0,in Australia,2011-2025,18,34,1,1542,169,46.72,2940,52.44,7,4,2,166,5
1,in Bangladesh,2015-2022,3,5,1,59,24,14.75,151,39.07,0,0,0,5,0
2,in England,2014-2023,17,33,0,1096,149,33.21,2111,51.91,2,5,4,129,1
3,in India,2011-2024,55,87,9,4336,254*,55.58,7311,59.30,14,13,7,474,16
4,in New Zealand,2014-2020,4,8,1,252,105*,36.00,438,57.53,1,1,0,38,1
5,in South Africa,2013-2024,9,18,0,891,153,49.50,1649,54.03,2,4,0,117,3
6,in Sri Lanka,2015-2017,6,10,1,394,103*,43.77,707,55.72,2,1,0,34,2
7,in West Indies,2011-2023,11,15,0,660,200,44.00,1301,50.73,2,3,2,64,2

In [14]:
file_path = 'fab4.xlsx'
k_df = pd.read_excel(file_path, sheet_name = 'Steven',index_col = None)
k_df.head(15)

,Country,Span,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100s,50s,0s,4s,6s
0,in Australia,2010-2025,58,100,16,5015,239,59.70,9203,54.49,18,19,6,528,26
1,in Bangladesh,2017-2017,2,4,0,119,58,29.75,218,54.58,0,1,0,15,0
2,in England,2010-2025,23,44,1,2334,215,54.27,3929,59.40,8,10,0,282,17
3,in India,2013-2023,10,19,3,805,178*,50.31,1827,44.06,3,1,1,85,4
4,in New Zealand,2016-2024,4,7,1,313,138,52.16,522,59.96,1,2,1,38,2
5,in Pakistan,2022-2022,3,4,0,226,78,56.50,606,37.29,0,3,0,22,0
6,in South Africa,2014-2018,6,11,1,411,100,41.10,771,53.30,1,2,1,54,5
7,in Sri Lanka,2016-2025,7,11,1,670,145*,67.00,1270,52.75,4,1,1,57,4
8,in U.A.E.,2014-2014,2,4,0,174,97,43.50,429,40.55,0,2,1,18,0
9,in West Indies,2015-2015,2,4,2,283,199,141.50,538,52.60,1,1,0,28,3